apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  security:
    adminSecret: cb-example-auth
    rbac:
      managed: true
      selector:
        matchLabels:
          cluster: cb-example
  buckets:
    managed: true
    selector:
      matchLabels:
        cluster: cb-example
  antiAffinity: true
  servers:
    - size: 3
      name: diq
      services:
        - data
        - index
        - query
      volumeMounts:
        default: couchbase
  networking:
    adminConsoleServices:
      - data
    adminConsoleServiceType: NodePort
    exposeAdminConsole: true
    exposedFeatureServiceType: NodePort
    exposedFeatures:
      - xdcr
  volumeClaimTemplates:
    - metadata:
        name: couchbase
      spec:
        storageClassName: gp2
        resources:
          requests:
            storage: 5Gi
  cluster:
    autoFailoverTimeout: 120s
    autoFailoverOnDataDiskIssues: true
    clusterName: cb-example
    indexStorageSetting: memory_optimized
    analyticsServiceMemoryQuota: 1Gi
    eventingServiceMemoryQuota: 256Mi
    searchServiceMemoryQuota: 256Mi
    autoFailoverMaxCount: 3
    dataServiceMemoryQuota: 256Mi
    autoFailoverOnDataDiskIssuesTimePeriod: 120s
    indexServiceMemoryQuota: 256Mi
    autoCompaction:
      databaseFragmentationThreshold:
        percent: 30
        size: 1Gi
      parallelCompaction: false
      timeWindow:
        abortCompactionOutsideWindow: true
        end: '06:00'
        start: '02:00'
      tombstonePurgeInterval: 72h
      viewFragmentationThreshold:
        percent: 30
        size: 1Gi
    autoFailoverServerGroup: false
  xdcr:
    managed: false
    selector:
      matchLabels:
        cluster: cb-example
  image: 'registry.connect.redhat.com/couchbase/server:6.6.5-1'
  logRetentionTime: 604800s
  logRetentionCount: 20
status:
  size: 0
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: staging
  labels:
    cluster: cb-example
spec:
  enableFlush: true
  compressionMode: passive
  enableIndexReplica: true
  ioPriority: high
  evictionPolicy: fullEviction
  memoryQuota: 128Mi
  replicas: 2
  conflictResolution: seqno
  type: couchbase
status: {}